services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8081}:80"
    environment:
      APP_NAME: ${APP_NAME:-Gegok12}
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_URL: ${APP_URL:-http://localhost}
      APP_KEY: ${APP_KEY:-}
      LOG_CHANNEL: ${LOG_CHANNEL:-daily}
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-gegok12}
      DB_USERNAME: ${DB_USERNAME:-gegok12}
      DB_PASSWORD: ${DB_PASSWORD:-gegok12}
      BROADCAST_DRIVER: ${BROADCAST_DRIVER:-log}
      CACHE_DRIVER: ${CACHE_DRIVER:-file}
      SESSION_DRIVER: ${SESSION_DRIVER:-file}
      SESSION_LIFETIME: ${SESSION_LIFETIME:-120}
      QUEUE_DRIVER: ${QUEUE_DRIVER:-database}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD:-null}
      REDIS_PORT: 6379
      MAIL_DRIVER: ${MAIL_DRIVER:-smtp}
      MAIL_HOST: ${MAIL_HOST:-mailhog}
      MAIL_PORT: ${MAIL_PORT:-1025}
      MAIL_USERNAME: ${MAIL_USERNAME:-null}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-null}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION:-null}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS:-hello@example.com}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME:-Gegok12}
      FILESYSTEM_DRIVER: ${FILESYSTEM_DRIVER:-local}
      FILESYSTEM_CLOUD: ${FILESYSTEM_CLOUD:-s3}
      TIMEZONE: ${TIMEZONE:-Asia/Kolkata}
      SCOUT_QUEUE: ${SCOUT_QUEUE:-true}
      RUN_MIGRATIONS: ${RUN_MIGRATIONS:-true}
      RUN_SEEDERS: ${RUN_SEEDERS:-false}
      WAIT_FOR_DB: ${WAIT_FOR_DB:-true}
    volumes:
      - storage_data:/var/www/html/storage
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailhog:
        condition: service_started

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_DATABASE:-gegok12}
      MYSQL_USER: ${DB_USERNAME:-gegok12}
      MYSQL_PASSWORD: ${DB_PASSWORD:-gegok12}
      TZ: ${TIMEZONE:-Asia/Kolkata}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "${MAILHOG_PORT:-8026}:8025"

volumes:
  mysql_data:
  redis_data:
  storage_data:
