services:
  db:
    image: mysql:8.0
    command: >-
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_DATABASE:-gegok12}
      MYSQL_USER: ${DB_USERNAME:-gegok12}
      MYSQL_PASSWORD: ${DB_PASSWORD:-gegok12}
      TZ: ${TIMEZONE:-Asia/Kolkata}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "${MAILHOG_PORT:-8026}:8025"
    networks:
      - mail

volumes:
  mysql_data:
  redis_data:

networks:
  backend:
  mail:
